services:
  # PHP Service
  app:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/app
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
      - ./database:/var/www/html/database
      - ./config:/var/www/html/config
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=your_password_here
    networks:
      - laravel

  # Nginx Service
  webserver:
    image: nginx:alpine
    ports:
      - "8050:80"
    volumes:
      - .:/var/www/html
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - app
    networks:
      - laravel

  # MySQL Service
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_password_here
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

# Volumes
volumes:
  dbdata:

# Networks
networks:
  laravel: